/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.9.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ExecuteMsg = {
  increment: {
    channel: string;
    [k: string]: unknown;
  };
};
export interface GetCountResponse {
  count: number;
  [k: string]: unknown;
}
export type IbcExecuteMsg = {
  increment: {
    [k: string]: unknown;
  };
};
export interface InstantiateMsg {
  [k: string]: unknown;
}
export type QueryMsg = {
  get_count: {
    channel: string;
    [k: string]: unknown;
  };
};