/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.9.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { ExecuteMsg, GetCountResponse, IbcExecuteMsg, InstantiateMsg, QueryMsg } from "./SimpleIbcCallback.types";
export interface SimpleIbcCallbackReadOnlyInterface {
  contractAddress: string;
  getCount: ({
    channel
  }: {
    channel: string;
  }) => Promise<GetCountResponse>;
}
export class SimpleIbcCallbackQueryClient implements SimpleIbcCallbackReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.getCount = this.getCount.bind(this);
  }

  getCount = async ({
    channel
  }: {
    channel: string;
  }): Promise<GetCountResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_count: {
        channel
      }
    });
  };
}
export interface SimpleIbcCallbackInterface extends SimpleIbcCallbackReadOnlyInterface {
  contractAddress: string;
  sender: string;
  increment: ({
    channel
  }: {
    channel: string;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export class SimpleIbcCallbackClient extends SimpleIbcCallbackQueryClient implements SimpleIbcCallbackInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.increment = this.increment.bind(this);
  }

  increment = async ({
    channel
  }: {
    channel: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      increment: {
        channel
      }
    }, fee, memo, funds);
  };
}