/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.9.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./SimpleIbcCallback.types";
import * as _1 from "./SimpleIbcCallback.client";
export namespace contracts {
  export const SimpleIbcCallback = { ..._0,
    ..._1
  };
}